export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export const SET_EDIT_JOB = 'SET_EDIT_JOB';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

// Phase 3: Activity Management Actions
export const GET_ACTIVITIES_BEGIN = 'GET_ACTIVITIES_BEGIN';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';

export const CREATE_ACTIVITY_BEGIN = 'CREATE_ACTIVITY_BEGIN';
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';
export const CREATE_ACTIVITY_ERROR = 'CREATE_ACTIVITY_ERROR';

export const UPDATE_ACTIVITY_BEGIN = 'UPDATE_ACTIVITY_BEGIN';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_ERROR = 'UPDATE_ACTIVITY_ERROR';

export const DELETE_ACTIVITY_BEGIN = 'DELETE_ACTIVITY_BEGIN';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';
export const DELETE_ACTIVITY_ERROR = 'DELETE_ACTIVITY_ERROR';

export const MARK_ACTIVITY_COMPLETE_BEGIN = 'MARK_ACTIVITY_COMPLETE_BEGIN';
export const MARK_ACTIVITY_COMPLETE_SUCCESS = 'MARK_ACTIVITY_COMPLETE_SUCCESS';
export const MARK_ACTIVITY_COMPLETE_ERROR = 'MARK_ACTIVITY_COMPLETE_ERROR';

export const GET_TIMELINE_ACTIVITIES_BEGIN = 'GET_TIMELINE_ACTIVITIES_BEGIN';
export const GET_TIMELINE_ACTIVITIES_SUCCESS = 'GET_TIMELINE_ACTIVITIES_SUCCESS';
export const GET_TIMELINE_ACTIVITIES_ERROR = 'GET_TIMELINE_ACTIVITIES_ERROR';

export const HANDLE_ACTIVITY_CHANGE = 'HANDLE_ACTIVITY_CHANGE';
export const CLEAR_ACTIVITY_FILTERS = 'CLEAR_ACTIVITY_FILTERS';
export const SET_SELECTED_JOB_FOR_TIMELINE = 'SET_SELECTED_JOB_FOR_TIMELINE';
export const CHANGE_ACTIVITY_PAGE = 'CHANGE_ACTIVITY_PAGE';

// Enhanced Activity Actions
export const SET_EDIT_ACTIVITY = 'SET_EDIT_ACTIVITY';
export const CLEAR_ACTIVITY_VALUES = 'CLEAR_ACTIVITY_VALUES';
export const SEARCH_ACTIVITIES_BEGIN = 'SEARCH_ACTIVITIES_BEGIN';
export const SEARCH_ACTIVITIES_SUCCESS = 'SEARCH_ACTIVITIES_SUCCESS';
export const GET_ACTIVITY_DETAILS_BEGIN = 'GET_ACTIVITY_DETAILS_BEGIN';
export const GET_ACTIVITY_DETAILS_SUCCESS = 'GET_ACTIVITY_DETAILS_SUCCESS';
